# .github/workflows/docker-publish.yml
# Builds Docker image, pushes to Amazon ECR, and triggers infra deployment with image digest

name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Docker image to Amazon ECR
    runs-on: ubuntu-latest

    env:
      ECR_REPO: viberoll-backend
      REGION: eu-west-2
      IMAGE_TAG: latest
      ACCOUNT_ID: 240398787204

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names "$ECR_REPO" --region "$REGION" >/dev/null 2>&1 || \
          aws ecr create-repository --repository-name "$ECR_REPO" --region "$REGION"

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin \
          $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPO:$IMAGE_TAG .

      - name: Tag, push image to ECR and capture digest
        id: push-image
        run: |
          IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO
          docker tag $ECR_REPO:$IMAGE_TAG $IMAGE_URI:$IMAGE_TAG
          docker push $IMAGE_URI:$IMAGE_TAG
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_URI:$IMAGE_TAG)
          echo "image_digest=$DIGEST" >> $GITHUB_OUTPUT

      - name: Trigger Infra Deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: celestn1/viberoll-infra
          event-type: deploy-trigger
          client-payload: |
            {
              "image_digest": "${{ steps.push-image.outputs.image_digest }}"
            }
