# viberoll-backend/.github/workflows/docker-publish.yml
# docker image build and push to Amazon ECR, then trigger infrastructure deployment

name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Docker image to Amazon ECR
    runs-on: ubuntu-latest

    env:
      ECR_REPO: viberoll-backend
      REGION: eu-west-2
      IMAGE_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin \
          240398787204.dkr.ecr.$REGION.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPO:$IMAGE_TAG .

      - name: Tag and push image to ECR
        run: |
          docker tag $ECR_REPO:$IMAGE_TAG 240398787204.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
          docker push 240398787204.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

      - name: Trigger Infra Deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: celestn1/viberoll-infra
          event-type: deploy-trigger

